Using pretrained: False
number of unique_entities -> 1861
number of unique_entities -> 1861
number of unique_entities -> 1861
Training size 2 Val size 2 Test size 2
Initialised relations and entities randomly
Graph created
length of graph keys is  1861
time taken  305.30330657958984
length of neighbors dict is  1861
Total triples count 627173, training triples 439073, validation_triples 62724, test_triples 125376
Opening node_neighbors pickle object
Initial entity dimensions torch.Size([1861, 50]) , relation dimensions torch.Size([275, 50])
Defining model
Only Conv model trained
Traceback (most recent call last):
  File "main.py", line 432, in <module>
    train_conv(args)
  File "main.py", line 328, in train_conv
    '{}/trained_{}.pth'.format(args.output_folder + 'gat', args.epochs_gat - 1)))
  File "/scratch/bz1030/anaconda3/envs/capstone/lib/python3.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/drugbank1861/gat/trained_899.pth'
