Using pretrained: False
number of unique_entities -> 2191
number of unique_entities -> 2191
number of unique_entities -> 2191
Initialised relations and entities randomly
Graph created
length of graph keys is  2191
time taken  792.6467702388763
length of neighbors dict is  2191
Total triples count 1702768, training triples 1193306, validation_triples 170472, test_triples 1704407
Opening node_neighbors pickle object
Initial entity dimensions torch.Size([2191, 50]) , relation dimensions torch.Size([316, 50])
Defining model

Model type -> GAT layer with 2 heads used , Initital Embeddings training
length of unique_entities  2191
Number of epochs 400

epoch->  0
Traceback (most recent call last):
  File "main.py", line 393, in <module>
    train_gat(args)
  File "main.py", line 254, in train_gat
    Corpus_, Corpus_.train_adj_matrix, train_indices, current_batch_2hop_indices)
  File "/scratch/bz1030/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/bz1030/relationPrediction/models.py", line 142, in forward
    edge_list, edge_type, edge_embed, edge_list_nhop, edge_type_nhop)
  File "/scratch/bz1030/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/bz1030/relationPrediction/models.py", line 65, in forward
    edge_list_nhop, edge_embed_nhop))
  File "/scratch/bz1030/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/bz1030/relationPrediction/layers.py", line 111, in forward
    (input[edge[0, :], :], input[edge[1, :], :], edge_embed[:, :]), dim=1).t()
RuntimeError: CUDA out of memory. Tried to allocate 4.18 GiB (GPU 0; 22.38 GiB total capacity; 19.91 GiB already allocated; 1.35 GiB free; 561.56 MiB cached)
